on:
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        uses: actions/setup-python@v2
      - name: run  
        run: python markdown_generator/photos.py
      
      - name: commit
        run: |
          git config --local user.email self@github.com
          git config --local user.name self
          git add .
          git commit -m "update" -a
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
