on:
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python markdown_generator/photos.py
      
      - name: commit
      - run: |
          git config --global user.email self@github.com
          git config --global user.name self
          git add .
          git commit -m "update" -a
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
